import numpy as np
import torch
from pathlib import Path

DATA_DIR = Path("data")
MVTEC_DIR = DATA_DIR / "mvtec_anomaly_detection"

DEVICE = (
    "mps"
    if torch.backends.mps.is_available()
    else "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


HISTO_NBINS_DICT_2018 = {
    '/Track/TrackITOverlapMonitor/ITASideTrack/IT1BottomBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITASideTrack/IT1TopBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITBottomTrack/IT1ASideBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITTopTrack/IT1CSideBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITCSideTrack/IT1BottomBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITCSideTrack/IT1TopBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITTopTrack/IT1ASideBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITBottomTrack/IT1CSideBox/hitres': 100,
    '/Muon/MuonPID/MonitorLong/hDist2_IM': 0,
    '/Muon/MuonPID/MonitorLong/hIMMomentum': 0,
    '/Muon/MuonPID/MonitorLong/hIMPT': 0,
    '/Muon/MuonPID/MonitorLong/hIMRegion': 0,
    '/Muon/MuonPID/MonitorLong/hNIMPStracksRatio': 0,
    '/Muon/MuonPID/MonitorLong/hNIMvsXM2': 0,
    '/Muon/MuonPID/MonitorLong/hNIMvsYM2': 0,
    '/Muon/MuonPID/MonitorLong/hNShared_IM': 0,
    '/Muon/MuonPID/MonitorLong/hNIMtracks': 0,
    '/JpsiDQMonitorPlots.MassPlotTool/peak/M_J_psi_1S': 50,
    '/MakeDstSel.DaughtersPlots/Mass(D0)': 100,
    '/MakeDstSel.DaughtersPlots/Mass(D~0)': 100,
    '/MakeDstSel.MotherPlots/#Delta Mass': 100,
    '/MakeDstSel.MotherPlots/Mass': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithBREM': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithECAL': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithHCAL': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithMUON': 100,
    '/PROTO/ChargedProtoPMoni/Long/trackToProtoEff': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithRICH': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithSPD': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithVELOdEdx': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithPRS': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/protosWithBREM': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/trackToProtoEff': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/protosWithVELOdEdx': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/protosWithRICH': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithECAL': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithHCAL': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithMUON': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/trackToProtoEff': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithRICH': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithSPD': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithPRS': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/ElectronANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/GhostANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/KaonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/MuonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/PionANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/ProtonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/ElectronANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/GhostANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/KaonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/MuonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/PionANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/ProtonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/ElectronANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/GhostANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/ProtonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/KaonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/MuonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/PionANN': 100,
    '/RICH/RichDecodingErrors/decodingErrors': 6,
    '/RICH/RichDecodingErrors/decodingErrorsByBoard': 144,
    '/RICH/RichRecPixelQC/Rich1/nActivePDs': 301,
    '/RICH/RichRecPixelQC/Rich1/nTotalPixs': 100,
    '/RICH/RichRecPixelQC/Rich1/nTotalPixsPerPD': 150,
    '/RICH/RichRecPixelClusters/Rich1/clusterSize': 101,
    '/RICH/RichRecPixelClusters/Rich2/clusterSize': 101,
    '/RICH/RichRecPixelQC/Rich2/nActivePDs': 301,
    '/RICH/RichRecPixelQC/Rich2/nTotalPixs': 100,
    '/RICH/RichRecPixelQC/Rich2/nTotalPixsPerPD': 150,
    '/RICH/RiLongTrkEff/All/effVChi2PDOF': 50,
    '/RICH/RiLongTrkEff/All/effVGhostProb': 50,
    '/RICH/RiLongTrkEff/All/effVPt': 50,
    '/RICH/RiLongTrkEff/All/effVP': 50,
    '/RICH/RiCKResLongTight/Rich1Gas/bottom/ckResAllPerPanel': 100,
    '/RICH/RiCKResLongTight/Rich1Gas/top/ckResAllPerPanel': 100,
    '/RICH/RiCKResLongTight/Rich2Gas/ASide-left/ckResAllPerPanel': 100,
    '/RICH/RiCKResLongTight/Rich2Gas/CSide-right/ckResAllPerPanel': 100,
    '/RichKsToPiPiSelPlots.MassPlotTool/all/M_KS0': 50,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/Eff. RICH acceptance': 0,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/Eff. RichDLL(pion-kaon)>0': 0,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/RichDLL(muon-pion)': 50,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/RichDLL(pion-kaon)': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/Eff. RICH acceptance': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/Eff. RichDLL(proton-pion)>0': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/RichDLL(proton-kaon)': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/RichDLL(proton-pion)': 50,
    '/RichLambdaToPrPiSelPlots.MassPlotTool/all/M_Lambda0': 50,
    '/RichLambdaToPrPiSelPlots.MassPlotTool/all/M_Lambda~0': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/Eff. RICH acceptance': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/Eff. RichDLL(pion-kaon)>0': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/RichDLL(muon-pion)': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/RichDLL(pion-kaon)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/RichDLL(muon-pion)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/RichDLL(pion-kaon)': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_D0': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_Dst_2010_minus': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_Dst_2010_plus': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_D~0': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/Eff. RICH acceptance': 0,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/Eff. RichDLL(kaon-pion)>0': 0,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/RichDLL(kaon-pion)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/RichDLL(proton-kaon)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/Eff. RICH acceptance': 0,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/Eff. RichDLL(pion-kaon)>0': 0,
    '/RichJPsiMuMuPlots.MassPlotTool/all/M_J_psi_1S': 50,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/Eff. RICH acceptance': 0,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/Eff. RichDLL(muon-pion)>0': 0,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/RichDLL(electron-muon)': 50,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/RichDLL(muon-pion)': 50,
    '/TT/TTClusterMonitor/Number of clusters vs TELL1': 48,
    '/IT/ITClusterMonitor/Number of clusters vs TELL1': 42,
    '/Track/TrackVertexMonitor/twoprong IP chi2 per dof': 100,
    '/Track/TrackVertexMonitor/twoprong decaylength significance': 100,
    '/Track/TrackVertexMonitor/twoprong mass (GeV)': 100,
    '/Track/TrackVertexMonitor/twoprong doca pull': 100,
    '/Track/TrackVertexMonitor/twoprong doca vs phi': 20,
    '/Track/TrackVertexMonitor/twoprong doca': 100,
    '/Track/TrackVertexMonitor/track IP X': 100,
    '/Track/TrackVertexMonitor/track IP X vs eta': 20,
    '/Track/TrackVertexMonitor/track IP Y vs phi': 20,
    '/Track/TrackVertexMonitor/track IP Y': 100,
    '/Track/TrackVertexMonitor/track IP Y vs eta': 20,
    '/Track/TrackVertexMonitor/track IP X vs phi': 20,
    '/Track/TrackVertexMonitor/fast track IP X': 100,
    '/Track/TrackVertexMonitor/fast track IP X vs eta': 20,
    '/Track/TrackVertexMonitor/fast track IP Y vs phi': 20,
    '/Track/TrackVertexMonitor/fast track IP Y': 100,
    '/Track/TrackVertexMonitor/fast track IP Y vs eta': 20,
    '/Track/TrackVertexMonitor/fast track IP X vs phi': 20
}

HISTO_NBINS = [v for v in HISTO_NBINS_DICT_2018.values() if v != 0]


def prepare_histo_dict_2023():

    histo_nbins_dict = {'/TrackPV2HalfMonitor/Left-Right PV delta x ': 0,
                        '/TrackPV2HalfMonitor/Left-Right PV delta y ': 0,
                        '/DigitMonitorEcal/9': 832,
                        '/DigitMonitorHcal/9': 832,
                        '/Monitor_calo_only_pi0_moniPi0Monitor/Histogram': 50,
                        '/ClusterMonitorEcalClusters/nClusters': 100,
                        '/CaloFutureECALTimeAlignment/FakeTAE_ADC': 400,
                        '/CaloFutureHCALTimeAlignment/FakeTAE_ADC': 400,
                        '/MuonMonitor/LinksInError_M2': 272,
                        '/MuonMonitor/LinksInError_M3': 128,
                        '/MuonMonitor/LinksInError_M4': 80,
                        '/MuonMonitor/LinksInError_M5': 96,
                        '/MuonMonitor/LinksInError_M2_A': 136,
                        '/MuonMonitor/LinksInError_M2_C': 136,
                        '/MuonMonitor/LinksInError_M3Q1': 32,
                        '/MuonMonitor/LinksInError_M3Q2': 32,
                        '/MuonMonitor/LinksInError_M3Q3': 32,
                        '/MuonMonitor/LinksInError_M3Q4': 32,
                        '/MuonMonitor/LinksInError_M4Q1': 20,
                        '/MuonMonitor/LinksInError_M4Q2': 20,
                        '/MuonMonitor/LinksInError_M4Q3': 20,
                        '/MuonMonitor/LinksInError_M4Q4': 20,
                        '/MuonMonitor/LinksInError_M5Q1': 24,
                        '/MuonMonitor/LinksInError_M5Q2': 24,
                        '/MuonMonitor/LinksInError_M5Q3': 24,
                        '/MuonMonitor/LinksInError_M5Q4': 24,
                        '/Hlt1KsToPiPi/ks_mass': 100,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/m': 100,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/pt': 80,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/eta': 40,
                        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/m': 100,
                        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/pt': 80,
                        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/eta': 40,
                        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/ipchi2': 64,
                        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/vchi2': 64,
                        '/Hlt2PID_JpsiToMuMumTagged_Detached/m': 100,
                        '/Hlt2PID_JpsiToMuMumTagged_Detached/pt': 80,
                        '/Hlt2PID_JpsiToMuMumTagged_Detached/eta': 40,
                        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/m': 100,
                        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/pt': 80,
                        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/eta': 40,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/D0_logIPCHI2': 60,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/D0_Daughters_Pasy': 60,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/D0_Daughters_PTasy': 60,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/pi_PIDk': 60,
                        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/K_PIDk': 60,
                        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/D0_M_plus': 60,
                        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/D0_M_minus': 60,
                        '/Hlt2PID_JpsiToMuMumTagged_Detached/probe_PIDmu': 60,
                        '/Hlt2PID_JpsiToMuMumTagged_Detached/probe_isMuon': 2,
                        '/Hlt2PID_JpsiToMuMumTagged_Detached/probe_pass_P': 75,
                        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/probe_hasBrem': 2,
                        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/probe_ECALPIDe': 60,
                        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/probe_BREMPIDe': 60,
                        '/Hlt2PID_KsToPiPi_LL/Ks_FDlog': 60,
                        '/Hlt2PID_KsToPiPi_DD/Ks_FDlog': 60,
                        '/RICH/HitMaps/Rich1/PixelMap': 206701,
                        '/RICH/HitMaps/Rich1/nHits': 35000,
                        '/RICH/RiCKResLong/Rich1Gas/top/ckResAllPerPanel': 100,
                        '/RICH/RiCKResLong/Rich1Gas/bottom/ckResAllPerPanel': 100,
                        '/RICH/HitMaps/Rich2/PixelMap2': 257785,
                        '/RICH/HitMaps/Rich2/nHits': 35000,
                        '/RICH/RiCKResLong/Rich2Gas/ASide-left/ckResAllPerPanel': 100,
                        '/RICH/RiCKResLong/Rich2Gas/CSide-right/ckResAllPerPanel': 100,
                        '/RICH/RichDLLsLong/below_threshold/dll': 100,
                        '/RICH/RichDLLsLong/deuteron/dll': 100,
                        '/RICH/RichDLLsLong/electron/dll': 100,
                        '/RICH/RichDLLsLong/kaon/dll': 100,
                        '/RICH/RichDLLsLong/muon/dll': 100,
                        '/RICH/RichDLLsLong/proton/dll': 100,
                        '/FTLiteClusterMonitor/Clusters_QuarterVsSiPM': 0,
                        '/Stat/LHCb/Allen/R_gather_selections/Hlt1KsToPiPiPass.value': 0,
                        '/TrackMonitor/Ttrack/TrackStateAtTUpX': 200,
                        '/TrackMonitor/Ttrack/TrackStateAtTDownX': 200,
                        '/LHCCOM/LHC.LHCb.Internal.Luminosity.Mu': 0,
                        '/LHCCOM/LHC.LHCb.Internal.Luminosity.Mu_calo': 0,
                        '/pv_beamline_cleanup/smogpv_z': 100,
                        '/SMOG2_kstopipi_line/ks_mass': 0,
                        '/SMOG2_dimuon_highmass_line/SMOG2_dimuon_mass': 0,
                        '/Config.PE411pr': 0,
                        '/Config.PE412pr': 0,
                        '/Config.DummySB': 0,
                        '/MonitorDetectorCorrelations/VeloScifiHitsCorrelation': 40000,
                        '/MonitorDetectorCorrelations/VeloMuonHitsCorrelation': 40000,
                        '/MonitorDetectorCorrelations/ScifiMuonHitsCorrelation': 40000,
                        '/MonitorDetectorCorrelations/ScifiRICH1HitsCorrelation': 40000,
                        '/MonitorDetectorCorrelations/ScifiRICH2HitsCorrelation': 40000,
                        '/MonitorDetectorCorrelations/ScifiECALCorrelation': 40000,
                        '/MonitorDetectorCorrelations/ScifiHCALCorrelation': 40000,
                        '/MonitorECALEnergyTrackerHitsCorrelations/ECALVeloHitsCorrelation': 0,
                        '/MonitorDetectorCorrelations/ECALHCALCorrelation': 0,
                        '/TrackMonitor/Long/p': 100,
                        '/TrackMonitor/Long/pt': 100,
                        '/TrackMonitor/Long/eta': 50,
                        '/TrackMonitor/Long/phi': 50,
                        '/TrackMonitor/Long/multiplicity': 101,
                        '/TrackMonitor/Long/z_closest_tozaxis': 50,
                        '/TrackMonitor/Long/qop_firststate': 50,
                        '/TrackMonitor/Long/probChi2': 50,
                        '/TrackMonitor/Long/chi2_per_ndof': 50,
                        '/TrackVertexMonitor/track IP X': 50,
                        '/TrackVertexMonitor/track IP X vs phi': 20,
                        '/TrackVertexMonitor/track IP X vs eta': 20,
                        '/TrackVertexMonitor/track IP Y': 50,
                        '/TrackVertexMonitor/track IP Y vs phi': 20,
                        '/TrackVertexMonitor/track IP Y vs eta': 20,
                        '/TrackMonitor/Ttrack/p': 100,
                        '/TrackMonitor/Ttrack/pt': 100,
                        '/TrackMonitor/Ttrack/eta': 50,
                        '/TrackMonitor/Ttrack/phi': 50,
                        '/TrackMonitor/Ttrack/multiplicity': 101,
                        '/TrackMonitor/Ttrack/nFTHits': 16,
                        '/TrackMonitor/Ttrack/qop_firststate': 50,
                        '/TrackMonitor/Ttrack/probChi2': 50,
                        '/TrackMonitor/Ttrack/chi2_per_ndof': 50,
                        '/VPClusterMonitors/VPClustersPerEvent': 1001,
                        '/VPDQMonitorsAll/VPAsic0': 52,
                        '/VPDQMonitorsAll/VPAsic1': 52,
                        '/VPDQMonitorsAll/VPAsic2': 52,
                        '/VPDQMonitorsAll/VPAsic3': 52,
                        '/VPDQMonitorsAll/VPAsic4': 52,
                        '/VPDQMonitorsAll/VPAsic5': 52,
                        '/VPDQMonitorsAll/VPAsic6': 52,
                        '/VPDQMonitorsAll/VPAsic7': 52,
                        '/VPDQMonitorsAll/VPAsic8': 52,
                        '/VPDQMonitorsAll/VPAsic9': 52,
                        '/VPDQMonitorsAll/VPAsic10': 52,
                        '/VPDQMonitorsAll/VPAsic11': 52,
                        '/VPTrackMonitorBest/Forward/TracksCside/NtracksperEvent': 351,
                        '/VPTrackMonitorBest/Forward/TracksAside/NtracksperEvent': 351,
                        '/VPTrackMonitorBest/Forward/TracksCside/pseudoRapidity': 400,
                        '/VPTrackMonitorBest/Forward/TracksAside/pseudoRapidity': 400,
                        '/VPDQMonitorsAll/VPAsicmap': 624,
                        '/VPDQMonitorsAll/VPClusPerEvent': 1001,
                        '/TrackVertexMonitor/PV x position': 200,
                        '/TrackVertexMonitor/PV y position': 200,
                        '/TrackVertexMonitor/PV z position': 200,
                        '/TrackVertexMonitor/NumTracksPerPV': 50,
                        '/TrackVertexMonitor/NumBackTracksPerPV': 50,
                        '/TrackVertexMonitor/NumPrimaryVertices': 11,
                        '/TrackVertexMonitor/PV chisquare per dof': 150,
                        '/PrSciFiHitsMonitor/T1U': 2000,
                        '/PrSciFiHitsMonitor/T1V': 2000,
                        '/PrSciFiHitsMonitor/T1X1': 2000,
                        '/PrSciFiHitsMonitor/T1X2': 2000,
                        '/PrSciFiHitsMonitor/T2U': 2000,
                        '/PrSciFiHitsMonitor/T2V': 2000,
                        '/PrSciFiHitsMonitor/T2X1': 2000,
                        '/PrSciFiHitsMonitor/T2X2': 2000,
                        '/PrSciFiHitsMonitor/T3U': 2000,
                        '/PrSciFiHitsMonitor/T3V': 2000,
                        '/PrSciFiHitsMonitor/T3X1': 2000,
                        '/PrSciFiHitsMonitor/T3X2': 2000
                        }

    rebin_factors = {'/VPDQMonitorsAll/VPAsicmap': [2, 2],
                     '/DigitMonitorEcal/9': [2, 2],
                     '/DigitMonitorHcal/9': [2, 2],
                     '/CaloFutureECALTimeAlignment/FakeTAE_ADC': [2, 2],
                     '/CaloFutureHCALTimeAlignment/FakeTAE_ADC': [2, 2],
                     '/RICH/HitMaps/Rich1/PixelMap': [40, 40],
                     '/RICH/HitMaps/Rich2/PixelMap2': [40, 40],
                     '/FTLiteClusterMonitor/Clusters_QuarterVsSiPM': [1, 4],
                     '/MonitorDetectorCorrelations/VeloScifiHitsCorrelation': [20, 20],
                     '/MonitorDetectorCorrelations/VeloMuonHitsCorrelation': [20, 20],
                     '/MonitorDetectorCorrelations/ScifiMuonHitsCorrelation': [20, 20],
                     '/MonitorDetectorCorrelations/ScifiRICH1HitsCorrelation': [20, 20],
                     '/MonitorDetectorCorrelations/ScifiRICH2HitsCorrelation': [20, 20],
                     '/MonitorDetectorCorrelations/ScifiECALCorrelation': [20, 20],
                     '/MonitorDetectorCorrelations/ScifiHCALCorrelation': [20, 20],
                     '/MonitorECALEnergyTrackerHitsCorrelations/ECALVeloHitsCorrelation': [20, 20],
                     '/MonitorDetectorCorrelations/ECALHCALCorrelation': [20, 20],
                     '/PrSciFiHitsMonitor/T1U': 20,
                     '/PrSciFiHitsMonitor/T1V': 20,
                     '/PrSciFiHitsMonitor/T1X1': 20,
                     '/PrSciFiHitsMonitor/T1X2': 20,
                     '/PrSciFiHitsMonitor/T2U': 20,
                     '/PrSciFiHitsMonitor/T2V': 20,
                     '/PrSciFiHitsMonitor/T2X1': 20,
                     '/PrSciFiHitsMonitor/T2X2': 20,
                     '/PrSciFiHitsMonitor/T3U': 20,
                     '/PrSciFiHitsMonitor/T3V': 20,
                     '/PrSciFiHitsMonitor/T3X1': 20,
                     '/PrSciFiHitsMonitor/T3X2': 20,
                     '/VPDQMonitorsAll/VPClusPerEvent': 10,
                     '/VPTrackMonitorBest/Forward/TracksCside/pseudoRapidity': 4,
                     '/VPTrackMonitorBest/Forward/TracksAside/pseudoRapidity': 4,
                     '/VPClusterMonitors/VPClustersPerEvent': 10,
                     '/VPDQMonitorsAll/VPClusPerEvent': 10,
                     '/RICH/HitMaps/Rich1/nHits': 200,
                     '/RICH/HitMaps/Rich2/nHits': 200,
                     '/TrackVertexMonitor/PV x position': 2,
                     '/TrackVertexMonitor/PV y position': 2,
                     '/TrackVertexMonitor/PV z position': 2,
                     }

    relevant_histos = [
        # '/TrackPV2HalfMonitor/Left-Right PV delta x ',
        # '/TrackPV2HalfMonitor/Left-Right PV delta y ',
        '/DigitMonitorEcal/9',
        '/DigitMonitorHcal/9',
        '/Monitor_calo_only_pi0_moniPi0Monitor/Histogram',
        '/ClusterMonitorEcalClusters/nClusters',
        '/CaloFutureECALTimeAlignment/FakeTAE_ADC',
        '/CaloFutureHCALTimeAlignment/FakeTAE_ADC',
        '/MuonMonitor/LinksInError_M2',
        '/MuonMonitor/LinksInError_M3',
        '/MuonMonitor/LinksInError_M4',
        '/MuonMonitor/LinksInError_M5',
        '/MuonMonitor/LinksInError_M2_A',
        '/MuonMonitor/LinksInError_M2_C',
        '/MuonMonitor/LinksInError_M3Q1',
        '/MuonMonitor/LinksInError_M3Q2',
        '/MuonMonitor/LinksInError_M3Q3',
        '/MuonMonitor/LinksInError_M3Q4',
        '/MuonMonitor/LinksInError_M4Q1',
        '/MuonMonitor/LinksInError_M4Q2',
        '/MuonMonitor/LinksInError_M4Q3',
        '/MuonMonitor/LinksInError_M4Q4',
        '/MuonMonitor/LinksInError_M5Q1',
        '/MuonMonitor/LinksInError_M5Q2',
        '/MuonMonitor/LinksInError_M5Q3',
        '/MuonMonitor/LinksInError_M5Q4',
        '/Hlt1KsToPiPi/ks_mass',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/m',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/pt',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/eta',
        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/m',
        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/pt',
        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/eta',
        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/ipchi2',
        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/vchi2',
        '/Hlt2PID_JpsiToMuMumTagged_Detached/m',
        '/Hlt2PID_JpsiToMuMumTagged_Detached/pt',
        '/Hlt2PID_JpsiToMuMumTagged_Detached/eta',
        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/m',
        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/pt',
        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/eta',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/D0_logIPCHI2',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/D0_Daughters_Pasy',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/D0_Daughters_PTasy',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/pi_PIDk',
        '/Hlt2Commissioning_D0ToKmPip_Hlt1D2KPiTOS/K_PIDk',
        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/D0_M_plus',
        '/Hlt2Commissioning_DpToKmPipPip_Hlt1TrackMVATOS/D0_M_minus',
        '/Hlt2PID_JpsiToMuMumTagged_Detached/probe_PIDmu',
        '/Hlt2PID_JpsiToMuMumTagged_Detached/probe_isMuon',
        '/Hlt2PID_JpsiToMuMumTagged_Detached/probe_pass_P',
        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/probe_hasBrem',
        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/probe_ECALPIDe',
        '/Hlt2PID_BToJpsiK_JpsiToEmbremEpbremTagged/probe_BREMPIDe',
        '/Hlt2PID_KsToPiPi_LL/Ks_FDlog',
        '/Hlt2PID_KsToPiPi_DD/Ks_FDlog',
        '/RICH/HitMaps/Rich1/PixelMap',
        '/RICH/HitMaps/Rich1/nHits',
        '/RICH/RiCKResLong/Rich1Gas/top/ckResAllPerPanel',
        '/RICH/RiCKResLong/Rich1Gas/bottom/ckResAllPerPanel',
        '/RICH/HitMaps/Rich2/PixelMap2',
        '/RICH/HitMaps/Rich2/nHits',
        '/RICH/RiCKResLong/Rich2Gas/ASide-left/ckResAllPerPanel',
        '/RICH/RiCKResLong/Rich2Gas/CSide-right/ckResAllPerPanel',
        '/RICH/RichDLLsLong/below_threshold/dll',
        '/RICH/RichDLLsLong/deuteron/dll',
        '/RICH/RichDLLsLong/electron/dll',
        '/RICH/RichDLLsLong/kaon/dll',
        '/RICH/RichDLLsLong/muon/dll',
        '/RICH/RichDLLsLong/proton/dll',
        # '/FTLiteClusterMonitor/Clusters_QuarterVsSiPM',
        # '/Stat/LHCb/Allen/R_gather_selections/Hlt1KsToPiPiPass.value',
        '/TrackMonitor/Ttrack/TrackStateAtTUpX',
        '/TrackMonitor/Ttrack/TrackStateAtTDownX',
        # '/LHCCOM/LHC.LHCb.Internal.Luminosity.Mu',
        # '/LHCCOM/LHC.LHCb.Internal.Luminosity.Mu_calo',
        '/pv_beamline_cleanup/smogpv_z',
        # '/SMOG2_kstopipi_line/ks_mass',
        # '/SMOG2_dimuon_highmass_line/SMOG2_dimuon_mass',
        # '/Config.PE411pr',
        # '/Config.PE412pr',
        # '/Config.DummySB',
        '/MonitorDetectorCorrelations/VeloScifiHitsCorrelation',
        '/MonitorDetectorCorrelations/VeloMuonHitsCorrelation',
        '/MonitorDetectorCorrelations/ScifiMuonHitsCorrelation',
        '/MonitorDetectorCorrelations/ScifiRICH1HitsCorrelation',
        '/MonitorDetectorCorrelations/ScifiRICH2HitsCorrelation',
        '/MonitorDetectorCorrelations/ScifiECALCorrelation',
        '/MonitorDetectorCorrelations/ScifiHCALCorrelation',
        # '/MonitorECALEnergyTrackerHitsCorrelations/ECALVeloHitsCorrelation',
        # '/MonitorDetectorCorrelations/ECALHCALCorrelation',
        '/TrackMonitor/Long/p',
        '/TrackMonitor/Long/pt',
        '/TrackMonitor/Long/eta',
        '/TrackMonitor/Long/phi',
        '/TrackMonitor/Long/multiplicity',
        '/TrackMonitor/Long/z_closest_tozaxis',
        '/TrackMonitor/Long/qop_firststate',
        '/TrackMonitor/Long/probChi2',
        '/TrackMonitor/Long/chi2_per_ndof',
        '/TrackVertexMonitor/track IP X',
        '/TrackVertexMonitor/track IP X vs phi',
        '/TrackVertexMonitor/track IP X vs eta',
        '/TrackVertexMonitor/track IP Y',
        '/TrackVertexMonitor/track IP Y vs phi',
        '/TrackVertexMonitor/track IP Y vs eta',
        '/TrackMonitor/Ttrack/p',
        '/TrackMonitor/Ttrack/pt',
        '/TrackMonitor/Ttrack/eta',
        '/TrackMonitor/Ttrack/phi',
        '/TrackMonitor/Ttrack/multiplicity',
        '/TrackMonitor/Ttrack/nFTHits',
        '/TrackMonitor/Ttrack/qop_firststate',
        '/TrackMonitor/Ttrack/probChi2',
        '/TrackMonitor/Ttrack/chi2_per_ndof',
        '/VPClusterMonitors/VPClustersPerEvent',
        '/VPDQMonitorsAll/VPAsic0',
        '/VPDQMonitorsAll/VPAsic1',
        '/VPDQMonitorsAll/VPAsic2',
        '/VPDQMonitorsAll/VPAsic3',
        '/VPDQMonitorsAll/VPAsic4',
        '/VPDQMonitorsAll/VPAsic5',
        '/VPDQMonitorsAll/VPAsic6',
        '/VPDQMonitorsAll/VPAsic7',
        '/VPDQMonitorsAll/VPAsic8',
        '/VPDQMonitorsAll/VPAsic9',
        '/VPDQMonitorsAll/VPAsic10',
        '/VPDQMonitorsAll/VPAsic11',
        '/VPTrackMonitorBest/Forward/TracksCside/NtracksperEvent',
        '/VPTrackMonitorBest/Forward/TracksAside/NtracksperEvent',
        '/VPTrackMonitorBest/Forward/TracksCside/pseudoRapidity',
        '/VPTrackMonitorBest/Forward/TracksAside/pseudoRapidity',
        '/VPDQMonitorsAll/VPAsicmap',
        '/VPDQMonitorsAll/VPClusPerEvent',
        '/TrackVertexMonitor/PV x position',
        '/TrackVertexMonitor/PV y position',
        '/TrackVertexMonitor/PV z position',
        '/TrackVertexMonitor/NumTracksPerPV',
        '/TrackVertexMonitor/NumBackTracksPerPV',
        '/TrackVertexMonitor/NumPrimaryVertices',
        '/TrackVertexMonitor/PV chisquare per dof',
        '/PrSciFiHitsMonitor/T1U',
        '/PrSciFiHitsMonitor/T1V',
        '/PrSciFiHitsMonitor/T1X1',
        '/PrSciFiHitsMonitor/T1X2',
        '/PrSciFiHitsMonitor/T2U',
        '/PrSciFiHitsMonitor/T2V',
        '/PrSciFiHitsMonitor/T2X1',
        '/PrSciFiHitsMonitor/T2X2',
        '/PrSciFiHitsMonitor/T3U',
        '/PrSciFiHitsMonitor/T3V',
        '/PrSciFiHitsMonitor/T3X1',
        '/PrSciFiHitsMonitor/T3X2']

    # Compute the number of bins per histogram after rebinnning
    for h in relevant_histos:
        if h in rebin_factors.keys():
            if type(rebin_factors[h]) is list:
                histo_nbins_dict[h] = int(np.sqrt(histo_nbins_dict[h]) / rebin_factors[h][0]) * \
                    int(np.sqrt(histo_nbins_dict[h]) / rebin_factors[h][1])
            else:
                histo_nbins_dict[h] = int(
                    histo_nbins_dict[h] / rebin_factors[h])

    # For the moment, fix by hand a problem with non-divisible rebinning factors
    histo_nbins_dict['/RICH/HitMaps/Rich1/PixelMap'] = int(437/rebin_factors['/RICH/HitMaps/Rich1/PixelMap'][0]) *\
        int(473/rebin_factors['/RICH/HitMaps/Rich1/PixelMap'][1])
    histo_nbins_dict['/RICH/HitMaps/Rich2/PixelMap2'] = int(545/rebin_factors['/RICH/HitMaps/Rich2/PixelMap2'][0]) *\
        int(473/rebin_factors['/RICH/HitMaps/Rich2/PixelMap2'][1])
    histo_nbins_dict['/VPDQMonitorsAll/VPAsicmap'] = int(52/rebin_factors['/VPDQMonitorsAll/VPAsicmap'][0]) *\
        int(12/rebin_factors['/VPDQMonitorsAll/VPAsicmap'][1])
    histo_nbins_dict['/DigitMonitorEcal/9'] = int(64/rebin_factors['/DigitMonitorEcal/9'][0]) *\
        int(52/rebin_factors['/DigitMonitorEcal/9'][1])
    histo_nbins_dict['/DigitMonitorHcal/9'] = int(64/rebin_factors['/DigitMonitorHcal/9'][0]) *\
        int(52/rebin_factors['/DigitMonitorHcal/9'][1])

    return histo_nbins_dict


HISTO_NBINS_DICT_2023 = prepare_histo_dict_2023()
