import torch
from pathlib import Path

DATA_DIR = Path("data")

DEVICE = (
    "mps"
    if torch.backends.mps.is_available()
    else "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

HISTO_NBINS_DICT = {
    '/Track/TrackITOverlapMonitor/ITASideTrack/IT1BottomBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITASideTrack/IT1TopBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITBottomTrack/IT1ASideBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITTopTrack/IT1CSideBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITCSideTrack/IT1BottomBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITCSideTrack/IT1TopBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITTopTrack/IT1ASideBox/hitres': 100,
    '/Track/TrackITOverlapMonitor/ITBottomTrack/IT1CSideBox/hitres': 100,
    '/Muon/MuonPID/MonitorLong/hDist2_IM': 0,
    '/Muon/MuonPID/MonitorLong/hIMMomentum': 0,
    '/Muon/MuonPID/MonitorLong/hIMPT': 0,
    '/Muon/MuonPID/MonitorLong/hIMRegion': 0,
    '/Muon/MuonPID/MonitorLong/hNIMPStracksRatio': 0,
    '/Muon/MuonPID/MonitorLong/hNIMvsXM2': 0,
    '/Muon/MuonPID/MonitorLong/hNIMvsYM2': 0,
    '/Muon/MuonPID/MonitorLong/hNShared_IM': 0,
    '/Muon/MuonPID/MonitorLong/hNIMtracks': 0,
    '/JpsiDQMonitorPlots.MassPlotTool/peak/M_J_psi_1S': 50,
    '/MakeDstSel.DaughtersPlots/Mass(D0)': 100,
    '/MakeDstSel.DaughtersPlots/Mass(D~0)': 100,
    '/MakeDstSel.MotherPlots/#Delta Mass': 100,
    '/MakeDstSel.MotherPlots/Mass': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithBREM': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithECAL': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithHCAL': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithMUON': 100,
    '/PROTO/ChargedProtoPMoni/Long/trackToProtoEff': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithRICH': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithSPD': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithVELOdEdx': 100,
    '/PROTO/ChargedProtoPMoni/Long/protosWithPRS': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/protosWithBREM': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/trackToProtoEff': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/protosWithVELOdEdx': 100,
    '/PROTO/ChargedProtoPMoni/Upstream/protosWithRICH': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithECAL': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithHCAL': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithMUON': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/trackToProtoEff': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithRICH': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithSPD': 100,
    '/PROTO/ChargedProtoPMoni/Downstream/protosWithPRS': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/ElectronANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/GhostANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/KaonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/MuonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/PionANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Long/ProtonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/ElectronANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/GhostANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/KaonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/MuonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/PionANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Upstream/ProtonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/ElectronANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/GhostANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/ProtonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/KaonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/MuonANN': 100,
    '/PROTO/ChargedProtoANNPIDMoni/Downstream/PionANN': 100,
    '/RICH/RichDecodingErrors/decodingErrors': 6,
    '/RICH/RichDecodingErrors/decodingErrorsByBoard': 144,
    '/RICH/RichRecPixelQC/Rich1/nActivePDs': 301,
    '/RICH/RichRecPixelQC/Rich1/nTotalPixs': 100,
    '/RICH/RichRecPixelQC/Rich1/nTotalPixsPerPD': 150,
    '/RICH/RichRecPixelClusters/Rich1/clusterSize': 101,
    '/RICH/RichRecPixelClusters/Rich2/clusterSize': 101,
    '/RICH/RichRecPixelQC/Rich2/nActivePDs': 301,
    '/RICH/RichRecPixelQC/Rich2/nTotalPixs': 100,
    '/RICH/RichRecPixelQC/Rich2/nTotalPixsPerPD': 150,
    '/RICH/RiLongTrkEff/All/effVChi2PDOF': 50,
    '/RICH/RiLongTrkEff/All/effVGhostProb': 50,
    '/RICH/RiLongTrkEff/All/effVPt': 50,
    '/RICH/RiLongTrkEff/All/effVP': 50,
    '/RICH/RiCKResLongTight/Rich1Gas/bottom/ckResAllPerPanel': 100,
    '/RICH/RiCKResLongTight/Rich1Gas/top/ckResAllPerPanel': 100,
    '/RICH/RiCKResLongTight/Rich2Gas/ASide-left/ckResAllPerPanel': 100,
    '/RICH/RiCKResLongTight/Rich2Gas/CSide-right/ckResAllPerPanel': 100,
    '/RichKsToPiPiSelPlots.MassPlotTool/all/M_KS0': 50,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/Eff. RICH acceptance': 0,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/Eff. RichDLL(pion-kaon)>0': 0,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/RichDLL(muon-pion)': 50,
    '/RichKsToPiPiSelPlots.RichPlotTool.peak/pion/RichDLL(pion-kaon)': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/Eff. RICH acceptance': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/Eff. RichDLL(proton-pion)>0': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/RichDLL(proton-kaon)': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/proton/RichDLL(proton-pion)': 50,
    '/RichLambdaToPrPiSelPlots.MassPlotTool/all/M_Lambda0': 50,
    '/RichLambdaToPrPiSelPlots.MassPlotTool/all/M_Lambda~0': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/Eff. RICH acceptance': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/Eff. RichDLL(pion-kaon)>0': 0,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/RichDLL(muon-pion)': 50,
    '/RichLambdaToPrPiSelPlots.RichPlotTool.peak/pion/RichDLL(pion-kaon)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/RichDLL(muon-pion)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/RichDLL(pion-kaon)': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_D0': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_Dst_2010_minus': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_Dst_2010_plus': 50,
    '/RichDstarToD0PiSelPlots.MassPlotTool/all/M_D~0': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/Eff. RICH acceptance': 0,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/Eff. RichDLL(kaon-pion)>0': 0,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/RichDLL(kaon-pion)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/kaon/RichDLL(proton-kaon)': 50,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/Eff. RICH acceptance': 0,
    '/RichDstarToD0PiSelPlots.RichPlotTool.peak/pion/Eff. RichDLL(pion-kaon)>0': 0,
    '/RichJPsiMuMuPlots.MassPlotTool/all/M_J_psi_1S': 50,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/Eff. RICH acceptance': 0,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/Eff. RichDLL(muon-pion)>0': 0,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/RichDLL(electron-muon)': 50,
    '/RichJPsiMuMuPlots.RichPlotTool.peak/muon/RichDLL(muon-pion)': 50,
    '/TT/TTClusterMonitor/Number of clusters vs TELL1': 48,
    '/IT/ITClusterMonitor/Number of clusters vs TELL1': 42,
    '/Track/TrackVertexMonitor/twoprong IP chi2 per dof': 100,
    '/Track/TrackVertexMonitor/twoprong decaylength significance': 100,
    '/Track/TrackVertexMonitor/twoprong mass (GeV)': 100,
    '/Track/TrackVertexMonitor/twoprong doca pull': 100,
    '/Track/TrackVertexMonitor/twoprong doca vs phi': 20,
    '/Track/TrackVertexMonitor/twoprong doca': 100,
    '/Track/TrackVertexMonitor/track IP X': 100,
    '/Track/TrackVertexMonitor/track IP X vs eta': 20,
    '/Track/TrackVertexMonitor/track IP Y vs phi': 20,
    '/Track/TrackVertexMonitor/track IP Y': 100,
    '/Track/TrackVertexMonitor/track IP Y vs eta': 20,
    '/Track/TrackVertexMonitor/track IP X vs phi': 20,
    '/Track/TrackVertexMonitor/fast track IP X': 100,
    '/Track/TrackVertexMonitor/fast track IP X vs eta': 20,
    '/Track/TrackVertexMonitor/fast track IP Y vs phi': 20,
    '/Track/TrackVertexMonitor/fast track IP Y': 100,
    '/Track/TrackVertexMonitor/fast track IP Y vs eta': 20,
    '/Track/TrackVertexMonitor/fast track IP X vs phi': 20
}
